FROM nvcr.io/nvidia/pytorch:23.10-py3
WORKDIR /workspace

ARG PROXY=""

ENV DEBIAN_FRONTEND=noninteractive
ENV MAX_JOBS=16

RUN apt-get update && apt-get install -y \
  build-essential git wget tmux \
  ffmpeg freeglut3-dev \
  && apt-get clean autoclean && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/* \
  && http_proxy=${PROXY} https_proxy=${PROXY} pip install uv openpyxl

CMD bash
